services:
  app:
    container_name: studentparliamentsystem.api
    build:
      context: src/StudentParliamentSystem.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
#      - ASPNETCORE_URLS=https://+:8081;http://+:8080
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASSWORD}
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#    volumes:
#      - ${SSL_CERTIFICATE_FOLDER_PATH}:/https:ro
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine
    container_name: studentparliamentsystem.database
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: